language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
  - osx

notifications:
  email: false
branches:
  only:
    - master

install:
  - pip install .

before_script:
  - pip install pytest pytest-cov

script:
  - pytest --cov=./

after_success:
  - pip install codecov
  - codecov
